### PR TITLE
add support for auth method extension points

### PR DESCRIPTION
**Pull request by gyorokpeter**
Add ability to define custom auth methods. The auth method is invoked immediately before opening the connection, so for example it could generate a token to be passed in the Password field. The token generation might be an async function. The default "Username and Password" auth method returns the connection properties unchanged.

© 2021 Morgan Stanley.
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE MIT License. YOU MAY OBTAIN A COPY OF THE LICENSE AT https://github.com/jshinonome/vscode-q/blob/master/LICENSE.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Comment by mcleo-d** [comment]
Hi @jshinonome 👋🏻 

I'm James McLeod, FINOS Director of Community, and I'd like to invite you to the [FINOS KDB+ Project](https://github.com/finos/kdb/) call on **Monday 12th July 2021 at 9:00am EST / 2:00pm BST** where the call details can be found here ... https://github.com/finos/kdb/issues/50

During the call I'd like to introduce you to @alvin-c-shih, KDB+ Lead Maintainer from Morgan Stanley, and the KDB+ project team that also includes @gyorokpeter who raised this pull request.

Also on the agenda is @ColinEberhardt from Scott Logic who is introducing the team to `KDB Studio 2 Prototype` that's found in the following issue https://github.com/finos/kdb/issues/51 as we'd really appreciate your input and feedback.

Thanks so much for considering this request and I look forward to hearing from you soon.

James.

**Comment by jshinonome** [comment]
Hi @mcleo-d 

Thanks for the invitation. I would be happy to join the meeting. Looking forward to meeting you during the meeting.

Kind regards,
Jo

**Comment by bobdguan** [comment]
@jshinonome fyi, these guys worked on the Kerberos plugin for studios for kdb in our company, guess somehow they noticed my previous thread :)

**Comment by jshinonome** [comment]
Hi Bob, I guessed so :) I will work with them to get this sorted.

**Comment by bobdguan** [comment]
That would be great, thanks again!

**Comment by jshinonome** [comment]
You are welcome!

**Comment by jshinonome** [comment]
As discussed, I will update my extension, and allow it to load the authentication method from another plugin. Also, provide a prototype of auth plugin to @gyorokpeter.

**Comment by jshinonome** [comment]
@gyorokpeter vscode-q v2.2.7 allows using customized authentication. Please refer to this repo for details: https://github.com/jshinonome/vscode-q-auth
After you created vscode-q-auth yourself, you can manually install it from vscode. When Customized Authentication is checked, it will load vscode-q-auth and use getToken() before connecting to the process.
Happy to jump a meeting if you need any clarification.

**Pull request closed without merging**
