### PR TITLE
Env-paths

### PR DESCRIPTION
**Pull request by Yanpas**
Based on https://github.com/jshinonome/vscode-q/pull/58

Fixes https://github.com/jshinonome/vscode-q/issues/56

### CODE REVIEW

**Comment by jshinonome** [comment]
Please update the MR focus on the q-server-cfg change

**Comment by jshinonome** [comment]
@Yanpas Thank you. This looks great. Merging it.

**Comment by Yanpas** [comment]
Don't know if that's expected/by-design, but `dumpHistory` is never called and was never called:
```
git grep dumpHistory $(git rev-list --all)
```

**Comment by jshinonome** [comment]
yeah, I haven't figured out how to deal with History. To be honest, I rarely check the history panel.

**Pull request merged**
